# Generated by Django 4.1 on 2022-09-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_lessonview_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonview',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
